
[GaussianProcesses.GPClassifier]
":input_is_multivariate" = "`true`"
":package_uuid" = "891a1506-143c-57d2-908e-e1f8e92e6de9"
":load_path" = "MLJModels.GaussianProcesses_.GPClassifier"
":input_scitypes" = "`MLJBase.Continuous`"
":is_pure_julia" = "`true`"
":is_supervised" = "`true`"
":package_url" = "https://github.com/STOR-i/GaussianProcesses.jl"
":package_name" = "GaussianProcesses"
":name" = "GPClassifier"
":is_probabilistic" = "`false`"
":target_scitype" = "`Union{FiniteOrderedFactor, Multiclass}`"
":is_wrapper" = "`false`"

[DecisionTree.DecisionTreeRegressor]
":input_is_multivariate" = "`true`"
":package_uuid" = "7806a523-6efd-50cb-b5f6-3fa6f1930dbb"
":load_path" = "MLJModels.DecisionTree_.DecisionTreeRegressor"
":input_scitypes" = "`MLJBase.Continuous`"
":is_pure_julia" = "`true`"
":is_supervised" = "`true`"
":package_url" = "https://github.com/bensadeghi/DecisionTree.jl"
":package_name" = "DecisionTree"
":name" = "DecisionTreeRegressor"
":is_probabilistic" = "`false`"
":target_scitype" = "`MLJBase.Continuous`"
":is_wrapper" = "`false`"

[DecisionTree.DecisionTreeClassifier]
":input_is_multivariate" = "`true`"
":package_uuid" = "7806a523-6efd-50cb-b5f6-3fa6f1930dbb"
":load_path" = "MLJModels.DecisionTree_.DecisionTreeClassifier"
":input_scitypes" = "`MLJBase.Continuous`"
":is_pure_julia" = "`true`"
":is_supervised" = "`true`"
":package_url" = "https://github.com/bensadeghi/DecisionTree.jl"
":package_name" = "DecisionTree"
":name" = "DecisionTreeClassifier"
":is_probabilistic" = "`true`"
":target_scitype" = "`Union{FiniteOrderedFactor, Multiclass}`"
":is_wrapper" = "`false`"

[ScikitLearn.SVMLClassifier]
":input_is_multivariate" = "`true`"
":package_uuid" = "3646fa90-6ef7-5e7e-9f22-8aca16db6324"
":load_path" = "MLJModels.ScikitLearn_.SVMLClassifier"
":input_scitypes" = "`MLJBase.Continuous`"
":is_pure_julia" = "`false`"
":is_supervised" = "`true`"
":package_url" = "https://github.com/cstjean/ScikitLearn.jl"
":package_name" = "ScikitLearn"
":name" = "SVMLClassifier"
":is_probabilistic" = "`false`"
":target_scitype" = "`Union{FiniteOrderedFactor, Multiclass}`"
":is_wrapper" = "`false`"

[ScikitLearn.SVMNuClassifier]
":input_is_multivariate" = "`true`"
":package_uuid" = "3646fa90-6ef7-5e7e-9f22-8aca16db6324"
":load_path" = "MLJModels.ScikitLearn_.SVMNuClassifier"
":input_scitypes" = "`MLJBase.Continuous`"
":is_pure_julia" = "`false`"
":is_supervised" = "`true`"
":package_url" = "https://github.com/cstjean/ScikitLearn.jl"
":package_name" = "ScikitLearn"
":name" = "SVMNuClassifier"
":is_probabilistic" = "`false`"
":target_scitype" = "`Union{FiniteOrderedFactor, Multiclass}`"
":is_wrapper" = "`false`"

[ScikitLearn.SVMRegressor]
":input_is_multivariate" = "`true`"
":package_uuid" = "3646fa90-6ef7-5e7e-9f22-8aca16db6324"
":load_path" = "MLJModels.ScikitLearn_.SVMRegressor"
":input_scitypes" = "`MLJBase.Continuous`"
":is_pure_julia" = "`false`"
":is_supervised" = "`true`"
":package_url" = "https://github.com/cstjean/ScikitLearn.jl"
":package_name" = "ScikitLearn"
":name" = "SVMRegressor"
":is_probabilistic" = "`false`"
":target_scitype" = "`MLJBase.Continuous`"
":is_wrapper" = "`false`"

[ScikitLearn.SVMClassifier]
":input_is_multivariate" = "`true`"
":package_uuid" = "3646fa90-6ef7-5e7e-9f22-8aca16db6324"
":load_path" = "MLJModels.ScikitLearn_.SVMClassifier"
":input_scitypes" = "`MLJBase.Continuous`"
":is_pure_julia" = "`false`"
":is_supervised" = "`true`"
":package_url" = "https://github.com/cstjean/ScikitLearn.jl"
":package_name" = "ScikitLearn"
":name" = "SVMClassifier"
":is_probabilistic" = "`false`"
":target_scitype" = "`Union{FiniteOrderedFactor, Multiclass}`"
":is_wrapper" = "`false`"

[ScikitLearn.SVMLRegressor]
":input_is_multivariate" = "`true`"
":package_uuid" = "3646fa90-6ef7-5e7e-9f22-8aca16db6324"
":load_path" = "MLJModels.ScikitLearn_.SVMLRegressor"
":input_scitypes" = "`MLJBase.Continuous`"
":is_pure_julia" = "`false`"
":is_supervised" = "`true`"
":package_url" = "https://github.com/cstjean/ScikitLearn.jl"
":package_name" = "ScikitLearn"
":name" = "SVMLRegressor"
":is_probabilistic" = "`false`"
":target_scitype" = "`MLJBase.Continuous`"
":is_wrapper" = "`false`"

[ScikitLearn.SVMNuRegressor]
":input_is_multivariate" = "`true`"
":package_uuid" = "3646fa90-6ef7-5e7e-9f22-8aca16db6324"
":load_path" = "MLJModels.ScikitLearn_.SVMNuRegressor"
":input_scitypes" = "`MLJBase.Continuous`"
":is_pure_julia" = "`false`"
":is_supervised" = "`true`"
":package_url" = "https://github.com/cstjean/ScikitLearn.jl"
":package_name" = "ScikitLearn"
":name" = "SVMNuRegressor"
":is_probabilistic" = "`false`"
":target_scitype" = "`MLJBase.Continuous`"
":is_wrapper" = "`false`"

[Clustering.KMeans]
":input_is_multivariate" = "`true`"
":package_uuid" = "aaaa29a8-35af-508c-8bc3-b662a17a0fe5"
":load_path" = "MLJModels.Clustering_.KMeans"
":input_scitypes" = "`MLJBase.Continuous`"
":is_pure_julia" = "`true`"
":is_supervised" = "`false`"
":package_url" = "https://github.com/JuliaStats/Clustering.jl"
":package_name" = "Clustering"
":name" = "KMeans"
":output_scitypes" = "`MLJBase.Continuous`"
":output_is_multivariate" = "`true`"
":is_wrapper" = "`false`"

[Clustering.KMedoids]
":input_is_multivariate" = "`true`"
":package_uuid" = "aaaa29a8-35af-508c-8bc3-b662a17a0fe5"
":load_path" = "MLJModels.Clustering_.KMedoids"
":input_scitypes" = "`MLJBase.Continuous`"
":is_pure_julia" = "`true`"
":is_supervised" = "`false`"
":package_url" = "https://github.com/JuliaStats/Clustering.jl"
":package_name" = "Clustering"
":name" = "KMedoids"
":output_scitypes" = "`MLJBase.Continuous`"
":output_is_multivariate" = "`true`"
":is_wrapper" = "`false`"

[GLM.OLSRegressor]
":input_is_multivariate" = "`true`"
":package_uuid" = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
":load_path" = "MLJModels.GLM_.OLSRegressor"
":input_scitypes" = "`MLJBase.Continuous`"
":is_pure_julia" = "`true`"
":is_supervised" = "`true`"
":package_url" = "https://github.com/JuliaStats/GLM.jl"
":package_name" = "GLM"
":name" = "OLSRegressor"
":is_probabilistic" = "`true`"
":target_scitype" = "`MLJBase.Continuous`"
":is_wrapper" = "`false`"

[GLM.GLMCountRegressor]
":input_is_multivariate" = "`true`"
":package_uuid" = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
":load_path" = "MLJModels.GLM_.GLMCountRegressor"
":input_scitypes" = "`MLJBase.Continuous`"
":is_pure_julia" = "`true`"
":is_supervised" = "`true`"
":package_url" = "https://github.com/JuliaStats/GLM.jl"
":package_name" = "GLM"
":name" = "GLMCountRegressor"
":is_probabilistic" = "`true`"
":target_scitype" = "`MLJBase.Count`"
":is_wrapper" = "`false`"

[NaiveBayes.GaussianNBClassifier]
":input_is_multivariate" = "`true`"
":package_uuid" = "9bbee03b-0db5-5f46-924f-b5c9c21b8c60"
":load_path" = "MLJModels.NaiveBayes_.GaussianNBClassifier"
":input_scitypes" = "`MLJBase.Continuous`"
":is_pure_julia" = "`true`"
":is_supervised" = "`true`"
":package_url" = "https://github.com/dfdx/NaiveBayes.jl"
":package_name" = "NaiveBayes"
":name" = "GaussianNBClassifier"
":is_probabilistic" = "`true`"
":target_scitype" = "`Union{FiniteOrderedFactor, Multiclass}`"
":is_wrapper" = "`false`"

[NaiveBayes.MultinomialNBClassifier]
":input_is_multivariate" = "`true`"
":package_uuid" = "9bbee03b-0db5-5f46-924f-b5c9c21b8c60"
":load_path" = "MLJModels.NaiveBayes_.MultinomialNBClassifier"
":input_scitypes" = "`MLJBase.Count`"
":is_pure_julia" = "`true`"
":is_supervised" = "`true`"
":package_url" = "https://github.com/dfdx/NaiveBayes.jl"
":package_name" = "NaiveBayes"
":name" = "MultinomialNBClassifier"
":is_probabilistic" = "`true`"
":target_scitype" = "`Union{FiniteOrderedFactor, Multiclass}`"
":is_wrapper" = "`false`"

[XGBoost.XGBoostCount]
":input_is_multivariate" = "`true`"
":package_uuid" = "009559a3-9522-5dbb-924b-0b6ed2b22bb9"
":load_path" = "MLJModels.XGBoost_.XGBoostCount"
":input_scitypes" = "`MLJBase.Continuous`"
":is_pure_julia" = "`false`"
":is_supervised" = "`true`"
":package_url" = "https://github.com/dmlc/XGBoost.jl"
":package_name" = "XGBoost"
":name" = "XGBoostCount"
":is_probabilistic" = "`false`"
":target_scitype" = "`MLJBase.Count`"
":is_wrapper" = "`false`"

[XGBoost.XGBoostRegressor]
":input_is_multivariate" = "`true`"
":package_uuid" = "009559a3-9522-5dbb-924b-0b6ed2b22bb9"
":load_path" = "MLJModels.XGBoost_.XGBoostRegressor"
":input_scitypes" = "`MLJBase.Continuous`"
":is_pure_julia" = "`false`"
":is_supervised" = "`true`"
":package_url" = "https://github.com/dmlc/XGBoost.jl"
":package_name" = "XGBoost"
":name" = "XGBoostRegressor"
":is_probabilistic" = "`false`"
":target_scitype" = "`MLJBase.Continuous`"
":is_wrapper" = "`false`"

[XGBoost.XGBoostClassifier]
":input_is_multivariate" = "`true`"
":package_uuid" = "009559a3-9522-5dbb-924b-0b6ed2b22bb9"
":load_path" = "MLJModels.XGBoost_.XGBoostClassifier"
":input_scitypes" = "`MLJBase.Continuous`"
":is_pure_julia" = "`false`"
":is_supervised" = "`true`"
":package_url" = "https://github.com/dmlc/XGBoost.jl"
":package_name" = "XGBoost"
":name" = "XGBoostClassifier"
":is_probabilistic" = "`true`"
":target_scitype" = "`Union{FiniteOrderedFactor, Multiclass}`"
":is_wrapper" = "`false`"
